### ISSUE TITLE
Error Message No logger set for joomla_projects\robo\WaitForSeleniumStandaloneServer.

### ISSUE THREAD

**Issue by astridx** [joomla-projects/robo#2]
If I run tests with selenium standalone server I get the error message at the end:

```
ERROR: No logger set for joomla_projects\robo\WaitForSeleniumStandaloneServer. Use $this->task(Foo::class) rather than new Foo() in loadTasks to ensure the builder can initialize task the task, or use $this->collectionBuilder()->taskFoo() if creating one task from within another. 
in /var/www/html/gsoc16_browser-automated-tests/tests/codeception/vendor/consolidation/robo/src/Common/TaskIO.php:43

```

If I follow this message and change the line https://github.com/joomla-projects/robo/blob/master/src/loadTasks.php#L21
from

        return new WaitForSeleniumStandaloneServer();
to
	return $this->task(WaitForSeleniumStandaloneServer::class);

The message disappears. 

My first question: 
As I am not very experienced with Robo I am not sure, If I can change this line without negative side effects.

**Comment by jatitoam** [comment]
I honestly don't know the side effects, but let me try it with a big testing package to make sure it doesn't break anything.

Did you change anything in particular to start getting the error?

**Comment by astridx** [comment]
@jatitoam Thank you 
I have not changed anything with intention.
I have this error message from begin on. I thought all the time I have to check and it should be an error in my configuration. But because the tests are running I let everything like it was.
But know I realized that one of our GSOC students had the same error message. That is why I made this PR.
The student worked on Ubunut, like am do.

**Comment by rdeutz** [comment]
closing this here because we move all tasks to https://github.com/joomla-projects/robo-joomla repository
